const mongoose = require('mongoose');

const providerProfileSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, unique: true },
    businessName: { type: String, trim: true },
    domain: { type: String, trim: true },
    description: { type: String, trim: true },
    address: { type: String, trim: true },
    contactNumber: { type: String, trim: true },
    workingHours: { type: String, trim: true },
    appointmentInstructions: { type: String, trim: true },
    isComplete: { type: Boolean, default: false },
    
    // AI-generated fields for improved search and recommendation
    aiKeywords: {
      type: [String],
      default: [],
      description: 'AI-extracted professional keywords for searchability (e.g., ["consultation", "telemedicine", "experienced"])',
    },
    keywordsGeneratedAt: {
      type: Date,
      description: 'Timestamp when keywords were last generated by AI',
    },
  },
  { timestamps: true }
);

// user index is already created by unique: true, so we don't need to add it again
providerProfileSchema.index({ domain: 1 });
providerProfileSchema.index({ businessName: 'text', domain: 'text', description: 'text', aiKeywords: 'text' });

module.exports = mongoose.model('ProviderProfile', providerProfileSchema);
